version: '3.8'

volumes:
    db-data:

services:
    dev:
        container_name: quote_api_dev
        image: quote-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:debug
        ports:
            - 3000:3000
        networks:
            - quote-api-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: quote_api_prod
        image: quote-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 3000:3000
        networks:
            - quote-api-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    db:
        image: postgres:14.5-alpine
        ports:
            - '54334:5432'
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: poca
        volumes:
            - db-data:/var/lib/postgresql

networks:
    quote-api-network: